### ISSUE TITLE
Dockerfile and docker-compose.yml files for running Chiriboga in a container

### ISSUE THREAD

**Issue by mikeriley** [bobtheuberfish/chiriboga#127]
Follow the instructions at [??](https://github.com/bobtheuberfish/chiriboga/wiki/Running-locally) to populate the images in the image folder, then run "docker-compose up --build -d" to create and run the project in a container after saving the following file contents below:

Filename = Dockerfile:
```
FROM php:7.2-apache
COPY src/ /var/www/html/
EXPOSE 80
```

Filename = docker-compose.yml:
```
version: '3'
services:
  web:
    image: netrunner
    build: .
    container_name: netrunner
    restart: always
    ports:
      - "3000:80"
```
Once docker-compose has the container running, visit the machine running it with a web browser by opening http://<MACHINE_NAME>:3000.
